```{r setup}
library(ggplot2)
library(ggtree)
library(signals)
library(dendextend)
library(fishplot)
library(ctc)
library(adephylo)
library(data.table)
library(HMMcopy)

# library(getopt)
library(plyr)

library(matrixStats)
library(parallel)
library(RColorBrewer)



#-----------------------------------------------------------------------
# setwd("/Users/dinhngockhanh/CancerSimulator/R/")
# files_sources <- list.files(pattern = "*.r$")
# sapply(files_sources, source)
#-----------------------------------------------------------------------
devtools::install_github("dinhngockhanh/CancerSimulator")
devtools::load_all()
devtools::document()
```



```{r,fig.height=5,fig.width=10}
#====================================================   FIXED PARAMETERS
cell_lifespan                       <- 30
T_0                                 <- list(0,'year')
T_end                               <- list(80,'year')

Table_sample <- data.frame(Sample_ID=c('SA01'),Cell_count=c(3),Age_sample=c(80))

# Table_sample <- data.frame(Sample_ID=c('SA01'),Cell_count=c(500),Age_sample=c(80))

T_tau_step                          <- cell_lifespan/2
CN_bin_length                       <- 500000

            prob_CN_whole_genome_duplication    <- 0e-4
            prob_CN_missegregation              <- 0e-4
            prob_CN_chrom_arm_missegregation    <- 0e-4
            prob_CN_focal_amplification         <- 0e-4
            prob_CN_focal_deletion              <- 0e-4
            prob_CN_cnloh_interstitial          <- 0e-4
            prob_CN_cnloh_terminal              <- 0e-4

            prob_CN_focal_amplification_length  <- 0.01
            prob_CN_focal_deletion_length       <- 0.01
            prob_CN_cnloh_interstitial_length   <- 0.01
            prob_CN_cnloh_terminal_length       <- 0.01

            rate_driver                         <- 8e-16

rate_passenger                      <- 1e-11
bound_driver                        <- 3
            bound_average_ploidy    <- 4.5
            bound_homozygosity      <- 500
vec_time                            <- T_0[[1]]:T_end[[1]]
L                                   <- 10000
t_0                                 <- 20
k                                   <- 0.3
vec_cell_count                      <- L/(1+exp(-k*(vec_time-t_0)))
table_population_dynamics           <- cbind(vec_time,vec_cell_count)

            gc                      <- read.csv(file = '../data/gc_map_500kb.csv')
            gc_slope                <- 1.2
            gc_int                  <- 0
            sigma1                  <- 0.1
            num_reads               <- 1e6

model_variables   <- BUILD_general_variables(
    cell_lifespan=cell_lifespan,
    T_0=T_0,T_end=T_end,T_tau_step=T_tau_step,
    Table_sample=Table_sample,
    CN_bin_length=CN_bin_length,
    prob_CN_whole_genome_duplication=prob_CN_whole_genome_duplication,
    prob_CN_missegregation=prob_CN_missegregation,
    prob_CN_chrom_arm_missegregation=prob_CN_chrom_arm_missegregation,
    prob_CN_focal_amplification=prob_CN_focal_amplification,
    prob_CN_focal_deletion=prob_CN_focal_deletion,
    prob_CN_cnloh_interstitial=prob_CN_cnloh_interstitial,
    prob_CN_cnloh_terminal=prob_CN_cnloh_terminal,
    prob_CN_focal_amplification_length=prob_CN_focal_amplification_length,
    prob_CN_focal_deletion_length=prob_CN_focal_deletion_length,
    prob_CN_cnloh_interstitial_length=prob_CN_cnloh_interstitial_length,
    prob_CN_cnloh_terminal_length=prob_CN_cnloh_terminal_length,
    rate_driver=rate_driver,
    rate_passenger=rate_passenger,
    bound_driver=bound_driver,
    bound_average_ploidy=bound_average_ploidy,
    bound_homozygosity=bound_homozygosity,
    table_population_dynamics=table_population_dynamics,
    gc=gc,
    gc_slope=gc_slope,
    gc_int=gc_int,
    sigma1=sigma1,
    num_reads=num_reads)

# vec_driver_genes  <- c('TP53','BRCA1','BRCA2','MSH2','MSH6','ARID1A',
# 'STK11','BRAF','MLH1','PIK3R1','ERBB2','CTNNB1','AKT1','PPP2R1A')
# vec_driver_role   <- c('TSG','TSG','TSG','TSG','TSG','TSG',
# 'TSG','ONCOGENE','TSG','TSG','ONCOGENE','ONCOGENE','ONCOGENE','TSG')

vec_driver_genes  <- c('TP53','BRCA1','BRCA2','MSH2','MSH6','ARID1A',
# 'STK11','BRAF',
'MLH1','PIK3R1','ERBB2','CTNNB1',
# 'AKT1',
'PPP2R1A')
vec_driver_role   <- c('TSG','TSG','TSG','TSG','TSG','TSG',
# 'TSG','ONCOGENE',
'TSG','TSG','ONCOGENE','ONCOGENE',
# 'ONCOGENE',
'TSG')

            vec_driver_s      <- rep(0.003,length(vec_driver_genes))
            vec_driver_s[1]   <- 0.01
            vec_driver_s[2]   <- 0.005
            vec_driver_s[3]   <- 0.005

model_variables   <- BUILD_driver_library(model_variables=model_variables,vec_driver_genes=vec_driver_genes,vec_driver_role=vec_driver_role,vec_driver_s=vec_driver_s)

            cell_count        <- 20
            CN_matrix         <- BUILD_cn_normal_XX(model_variables$cn_info)
            drivers           <- list()
model_variables   <- BUILD_initial_population(model_variables=model_variables,cell_count=cell_count,CN_matrix=CN_matrix,drivers=drivers)









#==================================================   STUDY FOR WGD RATE
rate_missegregation         <- 1e-4
vec_rate_WGD                <- c(1e-6)
# vec_rate_WGD                <- c(1e-6,1e-5,1e-4)
# vec_rate_WGD                <- c(1e-6,1e-5,1e-4,1e-3)
# vec_rate_WGD                <- seq(1, 9, by = 2)*1e-4
n_simulations_per_batch     <- 1
model_name_prefix           <- 'SENSITIVITY-WGD'
simulation_statistics_all   <- list()
# pb <- txtProgressBar(
#     min = 1, max = length(vec_rate_WGD),
#     style = 3, width = 50, char = "="
# )
for (batch in 1:length(vec_rate_WGD)){
    # setTxtProgressBar(pb, batch)
    model_variables_batch   <- model_variables
    #   Fix value for rate of missegregation
    model_variables_batch$general_variables$Value[which(model_variables_batch$general_variables$Variable=='prob_CN_missegregation')] <- rate_missegregation
    #   Fix value for rate of WGD
    model_variables_batch$general_variables$Value[which(model_variables_batch$general_variables$Variable=='prob_CN_whole_genome_duplication')] <- vec_rate_WGD[batch]
    #   Save parameter set
    model_name              <- paste(model_name_prefix,'-',batch,sep='')
    SAVE_model_variables(model_name=model_name,model_variables=model_variables_batch)
    #   Run batch of simulations
    stage_final             <- 2
    n_clones_min            <- 1
    n_clones_max            <- Inf
    n_simulations           <- n_simulations_per_batch
    start_time_here <- Sys.time()
    simulation_statistics   <- simulator_full_program(model = model_name,
        n_simulations = n_simulations,
        stage_final = stage_final,
        n_clones_min = n_clones_min,
        n_clones_max = n_clones_max,

        save_simulation = FALSE,
        save_newick_tree = FALSE,
        save_cn_profile = FALSE,
        # format_cn_profile = "both",
        internal_nodes_cn_info = FALSE,
        model_readcount = TRUE,
        apply_HMM = TRUE,
        report_progress = FALSE,
        compute_parallel = TRUE,

        pseudo_corrected_readcount = TRUE
    )
    #   Save statistics of the simulation batch
    simulation_statistics_all[[batch]] <- simulation_statistics
    end_time_here <- Sys.time()
    print("RUN TIME:")
    print(end_time_here - start_time_here)
}
#   Plot the comparison
plot_comparison(simulation_statistics_all,
    vec_time_points = seq(0, 80, by = 1),
    legend_batches = paste('WGD rate = ', vec_rate_WGD, sep = ''),
    plotfile_prefix = model_name_prefix)









# #=======================================   STUDY FOR MISSEGREGATION RATE
# rate_WGD                    <- 1e-4
# vec_rate_missegregation     <- seq(1, 9, by = 2)*1e-4
# n_simulations_per_batch     <- 100
# model_name_prefix           <- 'SENSITIVITY-MISSEGREGATION'
# simulation_statistics_all   <- list()
# pb <- txtProgressBar(
#     min = 1, max = length(vec_rate_missegregation),
#     style = 3, width = 50, char = "="
# )
# for (batch in 1:length(vec_rate_missegregation)){
#     setTxtProgressBar(pb, batch)
#     model_variables_batch   <- model_variables
#     #   Fix value for rate of WGD
#     model_variables_batch$general_variables$Value[which(model_variables_batch$general_variables$Variable=='prob_CN_whole_genome_duplication')] <- rate_WGD
#     #   Fix value for rate of missegregation
#     model_variables_batch$general_variables$Value[which(model_variables_batch$general_variables$Variable=='prob_CN_missegregation')] <- vec_rate_missegregation[batch]
#     #   Save parameter set
#     model_name              <- paste(model_name_prefix,'-',batch,sep='')
#     SAVE_model_variables(model_name=model_name,model_variables=model_variables_batch)
#     #   Run batch of simulations
#     stage_final             <- 2
#     n_clones_min            <- 1
#     n_clones_max            <- Inf
#     n_simulations           <- n_simulations_per_batch
#     start_time_here <- Sys.time()
#     simulation_statistics   <- simulator_full_program(model = model_name,
#         n_simulations = n_simulations,
#         stage_final = stage_final,
#         n_clones_min = n_clones_min,
#         n_clones_max = n_clones_max,
#         save_simulation = FALSE,
#         save_newick_tree = FALSE,
#         save_cn_profile = FALSE,
#         format_cn_profile = "both",
#         internal_nodes_cn_info = FALSE,
#         model_readcount = FALSE,
#         report_progress = TRUE)
#     #   Save statistics of the simulation batch
#     simulation_statistics_all[[batch]] <- simulation_statistics
#     end_time_here <- Sys.time()
#     print("RUN TIME:")
#     print(end_time_here - start_time_here)
# }
# #   Plot the comparison
# plot_comparison(simulation_statistics_all,
#     vec_time_points = seq(0, 80, by = 1),
#     legend_batches = paste('Miss. rate = ', vec_rate_missegregation, sep = ''),
#     plotfile_prefix = model_name_prefix)
```
