```{r setup}
library(readxl)
library(scales)
#-----------------------------------------------------------------------
setwd("/Users/dinhngockhanh/CancerSimulator/R/")
files_sources <- list.files(pattern = "*.r$")
sapply(files_sources, source)
#-----------------------------------------------------------------------
# devtools::install_github("dinhngockhanh/CancerSimulator")
# library(CancerSimulator)
```



```{r,fig.height=5,fig.width=10}
cell_lifespan <- 1
T_0 <- list(0, "day")
T_end <- list(300, "day")
Table_sample <- data.frame(Sample_ID = c("SA"), Cell_count = c(Inf), Age_sample = c(T_end[[1]]))

T_tau_step <- cell_lifespan / 2
CN_bin_length <- 500000

selection_model <- "chrom-arm-selection"

prob_CN_whole_genome_duplication <- 0
model_CN_missegregation <- 'per_division'
prob_CN_missegregation <- 0
prob_CN_chrom_arm_missegregation <- 0
prob_CN_focal_amplification <- 0
prob_CN_focal_deletion <- 0
prob_CN_cnloh_interstitial <- 0
prob_CN_cnloh_terminal <- 0
model_CN_focal_amplification_length <- "beta"
model_CN_focal_deletion_length <- "beta"
prob_CN_focal_amplification_length_shape_1 <- 0.758304780825031
prob_CN_focal_amplification_length_shape_2 <- 5.33873409782625
prob_CN_focal_deletion_length_shape_1 <- 0.814054548726361
prob_CN_focal_deletion_length_shape_2 <- 6.16614890284825
prob_CN_cnloh_interstitial_length <- 0.005
prob_CN_cnloh_terminal_length <- 0.005
rate_driver <- 0
rate_passenger <- 1e-11

bound_driver <- 3
bound_average_ploidy <- 6
bound_maximum_CN <- 8
bound_homozygosity <- 0

vec_time <- T_0[[1]]:T_end[[1]]
vec_cell_count <- rep(1000,length(vec_time))
table_population_dynamics <- cbind(vec_time, vec_cell_count)

gc <- read.csv(file = system.file("extdata", "gc_map_500kb.csv", package = "CancerSimulator"))
gc_slope <- 1.2
gc_int <- 0
sigma1 <- 0.02642392
num_reads <- 3906632

model_variables_base <- BUILD_general_variables(
    cell_lifespan = cell_lifespan,
    T_0 = T_0, T_end = T_end, T_tau_step = T_tau_step,
    Table_sample = Table_sample,
    CN_bin_length = CN_bin_length,

    model_CN_missegregation = model_CN_missegregation,

    prob_CN_whole_genome_duplication = prob_CN_whole_genome_duplication,
    prob_CN_missegregation = prob_CN_missegregation,
    prob_CN_chrom_arm_missegregation = prob_CN_chrom_arm_missegregation,
    prob_CN_focal_amplification = prob_CN_focal_amplification,
    prob_CN_focal_deletion = prob_CN_focal_deletion,
    prob_CN_cnloh_interstitial = prob_CN_cnloh_interstitial,
    prob_CN_cnloh_terminal = prob_CN_cnloh_terminal,

    model_CN_focal_amplification_length = model_CN_focal_amplification_length,
    model_CN_focal_deletion_length = model_CN_focal_deletion_length,
    prob_CN_focal_amplification_length_shape_1 = prob_CN_focal_amplification_length_shape_1,
    prob_CN_focal_amplification_length_shape_2 = prob_CN_focal_amplification_length_shape_2,
    prob_CN_focal_deletion_length_shape_1 = prob_CN_focal_deletion_length_shape_1,
    prob_CN_focal_deletion_length_shape_2 = prob_CN_focal_deletion_length_shape_2,
    prob_CN_cnloh_interstitial_length = prob_CN_cnloh_interstitial_length,
    prob_CN_cnloh_terminal_length = prob_CN_cnloh_terminal_length,
    rate_driver = rate_driver,
    rate_passenger = rate_passenger,
    selection_model = selection_model,
    bound_driver = bound_driver,
    bound_average_ploidy = bound_average_ploidy,
    bound_maximum_CN = bound_maximum_CN,
    bound_homozygosity = bound_homozygosity,
    table_population_dynamics = table_population_dynamics,
    gc = gc,
    gc_slope = gc_slope,
    gc_int = gc_int,
    sigma1 = sigma1,
    num_reads = num_reads
)

arm_id <- c(paste(model_variables_base$cn_info$Chromosome, "p", sep = ""), paste(model_variables_base$cn_info$Chromosome, "q", sep = ""))
arm_chromosome <- rep(model_variables_base$cn_info$Chromosome, 2)
arm_start <- c(rep(1, length(model_variables_base$cn_info$Chromosome)), model_variables_base$cn_info$Centromere_location + 1)
arm_end <- c(model_variables_base$cn_info$Centromere_location, model_variables_base$cn_info$Bin_count)
arm_s <- rep(1, length(arm_id))
arm_s[which(arm_id == "1p")] <- 0.886307781235821
arm_s[which(arm_id == "2p")] <- 1.01825968094413
arm_s[which(arm_id == "3p")] <- 0.920530554894643
arm_s[which(arm_id == "4p")] <- 0.976827677204689
arm_s[which(arm_id == "5p")] <- 1.15969179661142
arm_s[which(arm_id == "6p")] <- 1.04997702081472
arm_s[which(arm_id == "7p")] <- 1.13777132552215
arm_s[which(arm_id == "8p")] <- 0.884012569028591
arm_s[which(arm_id == "9p")] <- 0.935174629285682
arm_s[which(arm_id == "10p")] <- 1.02799999379291
arm_s[which(arm_id == "11p")] <- 0.967134549774896
arm_s[which(arm_id == "12p")] <- 1.06959509411319
arm_s[which(arm_id == "13p")] <- 1
arm_s[which(arm_id == "14p")] <- 1
arm_s[which(arm_id == "15p")] <- 1
arm_s[which(arm_id == "16p")] <- 1.04513229635198
arm_s[which(arm_id == "17p")] <- 0.864520777388622
arm_s[which(arm_id == "18p")] <- 1.01592152467124
arm_s[which(arm_id == "19p")] <- 1.02814969243796
arm_s[which(arm_id == "20p")] <- 1.00368324400257
arm_s[which(arm_id == "21p")] <- 1
arm_s[which(arm_id == "22p")] <- 1
arm_s[which(arm_id == "Xp")] <- 1
arm_s[which(arm_id == "Yp")] <- 1

arm_s[which(arm_id == "1q")] <- 1.18666462081686
arm_s[which(arm_id == "2q")] <- 0.962046964747096
arm_s[which(arm_id == "3q")] <- 1.11600788103894
arm_s[which(arm_id == "4q")] <- 0.937701536089568
arm_s[which(arm_id == "5q")] <- 0.896394926675205
arm_s[which(arm_id == "6q")] <- 0.886499991701187
arm_s[which(arm_id == "7q")] <- 1.05243171270735
arm_s[which(arm_id == "8q")] <- 1.22076350654396
arm_s[which(arm_id == "9q")] <- 0.964639963793044
arm_s[which(arm_id == "10q")] <- 0.90108395332905
arm_s[which(arm_id == "11q")] <- 0.967049029726524
arm_s[which(arm_id == "12q")] <- 1.03537911097717
arm_s[which(arm_id == "13p")] <- 0.969546453082048
arm_s[which(arm_id == "14p")] <- 0.971985635416426
arm_s[which(arm_id == "15p")] <- 0.998823078653965
arm_s[which(arm_id == "16q")] <- 0.935335591311341
arm_s[which(arm_id == "17q")] <- 1.05238889818635
arm_s[which(arm_id == "18q")] <- 0.935292135865439
arm_s[which(arm_id == "19q")] <- 1.03037910158697
arm_s[which(arm_id == "20q")] <- 1.20848277950342
arm_s[which(arm_id == "21q")] <- 0.96470320220417
arm_s[which(arm_id == "22q")] <- 0.959601745948745
arm_s[which(arm_id == "Xq")] <- 1
arm_s[which(arm_id == "Yq")] <- 1

s_rate_scale <- 1

arm_s[which(arm_s > 1)] <- 1 + s_rate_scale * (arm_s[which(arm_s > 1)] - 1)
arm_s[which(arm_s < 1)] <- 1 / (1 + s_rate_scale * (1 / arm_s[which(arm_s < 1)] - 1))

model_variables_base <- BUILD_driver_library(
    model_variables = model_variables_base,
    table_arm_selection_rates = data.frame(Arm_ID = arm_id, Chromosome = arm_chromosome, Bin_start = arm_start, Bin_end = arm_end, s_rate = arm_s)
)

cell_count <- 1000
CN_matrix <- BUILD_cn_normal_XX(model_variables_base$cn_info)
drivers <- list()
model_variables_base <- BUILD_initial_population(
    model_variables = model_variables_base,
    cell_count = cell_count,
    CN_matrix = CN_matrix,
    drivers = drivers
)

model_prefix <- "WGD-vs-MISSEGREGATION-PER-DIVISION"
folder_workplace <- "WGD-vs-MISSEGREGATION-PER-DIVISION"
```



```{r}
# n_simulations_per_batch <- 1000
#
# var1_name <- "prob_CN_missegregation"
# var1_vals <- seq(1e-3, 1e-2, by = 1e-3)
#
# var2_name <- "prob_CN_whole_genome_duplication"
# var2_vals <- seq(1e-3, 1e-2, by = 1e-3)



n_simulations_per_batch <- 5

var1_name <- "prob_CN_missegregation"
var1_vals <- seq(1e-3, 1e-2, by = 1e-3)
var1_labs <- scientific(var1_vals)

var2_name <- "prob_CN_whole_genome_duplication"
var2_vals <- seq(1e-3, 1e-2, by = 1e-3)
var2_labs <- scientific(var2_vals)
```

```{r}
simulator_multivar(
    model_prefix = model_prefix, folder_workplace = folder_workplace,
    model_variables_base = model_variables_base,
    var1_name = var1_name, var1_vals = var1_vals, var1_labs = var1_labs,
    var2_name = var2_name, var2_vals = var2_vals, var2_labs = var2_labs,
    n_simulations = n_simulations_per_batch,
    stage_final = 3,
    compute_parallel = TRUE
)
```

```{r}
statistics_multivar_matrix(
    model_prefix = model_prefix, folder_workplace = folder_workplace,
    var1_name = var1_name, var1_vals = var1_vals, var1_labs = var1_labs,
    var2_name = var2_name, var2_vals = var2_vals, var2_labs = var2_labs,
    n_simulations = n_simulations_per_batch,
    plot_WGD = TRUE,
    plot_misseg = TRUE,
    compute_parallel = TRUE
)
```

```{r}
var2_fixed <- var2_labs[1]
statistics_multivar_vector(
    model_prefix = model_prefix, folder_workplace = folder_workplace,
    var1_name = var1_name, var1_labs = var1_labs,
    var2_name = var2_name, var2_labs = rep(var2_fixed, length(var1_labs)),
    var_labs = var1_vals, name_lab = "Probability of missegregation",
    plot_WGD = TRUE,
    n_simulations = n_simulations_per_batch,
    plotname = paste0(model_prefix, "_prob_CN_missegregation_varies_and_prob_CN_whole_genome_duplication=", var2_fixed),
    example_simulation = FALSE
)
```

```{r}
var1_fixed <- var1_labs[length(var1_labs)]
statistics_multivar_vector(
    model_prefix = model_prefix, folder_workplace = folder_workplace,
    var1_name = var1_name, var1_labs = rep(var1_fixed, length(var2_labs)),
    var2_name = var2_name, var2_labs = var2_labs,
    var_labs = var2_labs, name_lab = "Probability of WGD",
    plot_WGD = TRUE,
    n_simulations = n_simulations_per_batch,
    plotname = paste0(model_prefix, "_prob_CN_whole_genome_duplication_varies_and_prob_CN_missegregation=", var1_fixed),
    example_simulation = FALSE
)
```



```{r}
```
