```{r setup}
library(readxl)
#-----------------------------------------------------------------------
setwd("/Users/dinhngockhanh/CancerSimulator/R/")
files_sources <- list.files(pattern = "*.r$")
sapply(files_sources, source)
#-----------------------------------------------------------------------
# devtools::install_github("dinhngockhanh/CancerSimulator")
# library(CancerSimulator)
```



```{r}
cell_lifespan <- 30
T_0 <- list(0, "year")
T_end <- list(80, "year")
Table_sample <- data.frame(Sample_ID = c("SA01"), Cell_count = c(Inf), Age_sample = c(80))
T_tau_step <- cell_lifespan / 2
CN_bin_length <- 500000
selection_model <- "WGD-chrom-arm-selection"
# selection_model <- "chrom-arm-selection"
#------------------------------------------------------CNA PROBABILITIES
prob_CN_whole_genome_duplication <- 0e-4
prob_CN_missegregation <- 5e-5
prob_CN_chrom_arm_missegregation <- 0e-5
prob_CN_focal_amplification <- 0e-5
prob_CN_focal_deletion <- 0e-5
prob_CN_cnloh_interstitial <- 0e-5
prob_CN_cnloh_terminal <- 0e-5
model_CN_focal_amplification_length <- "beta"
model_CN_focal_deletion_length <- "beta"
prob_CN_focal_amplification_length_shape_1 <- 0.758304780825031
prob_CN_focal_amplification_length_shape_2 <- 5.33873409782625
prob_CN_focal_deletion_length_shape_1 <- 0.814054548726361
prob_CN_focal_deletion_length_shape_2 <- 6.16614890284825
prob_CN_cnloh_interstitial_length <- 0.005
prob_CN_cnloh_terminal_length <- 0.005
rate_driver <- 0
rate_passenger <- 1e-11
#---------------------------------------------------VIABILITY THRESHOLDS
# bound_driver <- 3
# bound_average_ploidy <- 6
# bound_homozygosity <- 0
# bound_maximum_CN <- Inf
# bound_maximum_CN_normalized <- 4

bound_driver <- Inf
bound_average_ploidy <- Inf
bound_homozygosity <- 0
bound_maximum_CN <- Inf
bound_maximum_CN_normalized <- 4
bound_WGD <- 1
#----------------------------------------------------POPULATION DYNAMICS
vec_time <- T_0[[1]]:T_end[[1]]
L <- 10000
t_0 <- 20
k <- 0.3
vec_cell_count <- L / (1 + exp(-k * (vec_time - t_0)))
table_population_dynamics <- cbind(vec_time, vec_cell_count)
#-----------------------------------------------------------------------
gc <- read.csv(file = system.file("extdata", "gc_map_500kb.csv", package = "CancerSimulator"))
gc_slope <- 1.2
gc_int <- 0
sigma1 <- 0.1
num_reads <- 2e6
model_variables_base <- BUILD_general_variables(
    cell_lifespan = cell_lifespan,
    T_0 = T_0, T_end = T_end, T_tau_step = T_tau_step,
    Table_sample = Table_sample,
    CN_bin_length = CN_bin_length,
    prob_CN_whole_genome_duplication = prob_CN_whole_genome_duplication,
    prob_CN_missegregation = prob_CN_missegregation,
    prob_CN_chrom_arm_missegregation = prob_CN_chrom_arm_missegregation,
    prob_CN_focal_amplification = prob_CN_focal_amplification,
    prob_CN_focal_deletion = prob_CN_focal_deletion,
    prob_CN_cnloh_interstitial = prob_CN_cnloh_interstitial,
    prob_CN_cnloh_terminal = prob_CN_cnloh_terminal,
    model_CN_focal_amplification_length = model_CN_focal_amplification_length,
    model_CN_focal_deletion_length = model_CN_focal_deletion_length,
    prob_CN_focal_amplification_length_shape_1 = prob_CN_focal_amplification_length_shape_1,
    prob_CN_focal_amplification_length_shape_2 = prob_CN_focal_amplification_length_shape_2,
    prob_CN_focal_deletion_length_shape_1 = prob_CN_focal_deletion_length_shape_1,
    prob_CN_focal_deletion_length_shape_2 = prob_CN_focal_deletion_length_shape_2,
    prob_CN_cnloh_interstitial_length = prob_CN_cnloh_interstitial_length,
    prob_CN_cnloh_terminal_length = prob_CN_cnloh_terminal_length,
    rate_driver = rate_driver,
    rate_passenger = rate_passenger,
    selection_model = selection_model,
    bound_driver = bound_driver,
    bound_maximum_CN = bound_maximum_CN,
    bound_average_ploidy = bound_average_ploidy,
    bound_homozygosity = bound_homozygosity,
    bound_maximum_CN_normalized = bound_maximum_CN_normalized,
    bound_WGD = bound_WGD,
    table_population_dynamics = table_population_dynamics,
    gc = gc,
    gc_slope = gc_slope,
    gc_int = gc_int,
    sigma1 = sigma1,
    num_reads = num_reads
)
arm_id <- c(paste(model_variables_base$cn_info$Chromosome, "p", sep = ""), paste(model_variables_base$cn_info$Chromosome, "q", sep = ""))
arm_chromosome <- rep(model_variables_base$cn_info$Chromosome, 2)
arm_start <- c(rep(1, length(model_variables_base$cn_info$Chromosome)), model_variables_base$cn_info$Centromere_location + 1)
arm_end <- c(model_variables_base$cn_info$Centromere_location, model_variables_base$cn_info$Bin_count)
arm_s <- rep(1, length(arm_id))

model_variables_base <- BUILD_driver_library(
    model_variables = model_variables_base,
    table_arm_selection_rates = data.frame(Arm_ID = arm_id, Chromosome = arm_chromosome, Bin_start = arm_start, Bin_end = arm_end, s_rate = arm_s)
)

cell_count <- 20
CN_matrix <- BUILD_cn_normal_autosomes(model_variables_base$cn_info)
drivers <- list()
model_variables_base <- BUILD_initial_population(
    model_variables = model_variables_base,
    cell_count = cell_count,
    CN_matrix = CN_matrix,
    drivers = drivers
)
model_variables_base <- CHECK_model_variables(model_variables_base)

model_prefix <- "WGD-and-ANEUPLOIDY"
folder_workplace <- "WGD-and-ANEUPLOIDY"
```

```{r}
model_variables_base$general_variables[nrow(model_variables_base$general_variables) + 1, ] <-
    c("alpha_aneuploidy", 1, "", "")
model_variables_base$general_variables$Value[which(model_variables_base$general_variables$Variable == "formula_CN_missegregation")] <-
    paste0("prob_CN_missegregation * ( (alpha_aneuploidy-1)*WGD_count + 1 )")
model_variables_base$general_variables$Value[which(model_variables_base$general_variables$Variable == "formula_CN_chrom_arm_missegregation")] <-
    paste0("prob_CN_chrom_arm_missegregation * ( (alpha_aneuploidy-1)*WGD_count + 1 )")
parameter_best <- read.csv("PAN-CANCER_fitted_parameters.csv")
######
######
######
######
######
parameter_best$Best_value[which(parameter_best$Type == "Arm_selection_rate" & parameter_best$Best_value == 1)] <-
    c(0.9920039, 0.9933136, 0.9952504, 0.9859580, 0.9887057, 0.9927065, 0.9871305,
        1.0010945, 0.9868608, 0.9964952, 0.9866928, 1.0026826, 0.9981111)
# parameter_best$Best_value[which(parameter_best$Type == "Arm_selection_rate" & parameter_best$Best_value == 1)] <-
#     runif(length(which(parameter_best$Type == "Arm_selection_rate" & parameter_best$Best_value == 1)), 0.9836265, 1.007644)
######
######
######
######
######
model_variables_base <- bulk_arm_CN_assign_paras(
    model_variables = model_variables_base,
    parameter_IDs = parameter_best$Variable,
    parameters = parameter_best$Best_value
)
```

```{r}
n_simulations_per_batch <- 50
# n_simulations_per_batch <- 1000

var1_name <- "prob_CN_whole_genome_duplication"
var2_name <- "alpha_aneuploidy"

var1_vals <- c(1e-5)
var2_vals <- c(200)

# var1_vals <- seq(1e-6, 1e-6, by = 1e-6)
# var2_vals <- seq(log2(100), log2(100))
```

```{r}
simulator_multivar(
    model_prefix = model_prefix, folder_workplace = folder_workplace,
    model_variables_base = model_variables_base,
    var1_name = var1_name, var1_vals = var1_vals,
    var2_name = var2_name, var2_vals = var2_vals,
    n_simulations = n_simulations_per_batch,
    stage_final = 3,
    compute_parallel = FALSE
    # compute_parallel = TRUE
)
```

```{r}
statistics_multivar_matrix(
    model_prefix = model_prefix, folder_workplace = folder_workplace,
    var1_name = var1_name, var1_vals = var1_vals,
    var2_name = var2_name, var2_vals = var2_vals,
    n_simulations = n_simulations_per_batch,
    plot_WGD = TRUE,
    # compute_parallel = FALSE
    compute_parallel = TRUE
)
```

```{r}
# var2_fixed <- var2_labs[1]
# statistics_multivar_vector(
#     model_prefix = model_prefix, folder_workplace = folder_workplace,
#     var1_name = var1_name, var1_vals = var1_vals,
#     var2_name = var2_name, var2_labs = rep(var2_fixed, length(var1_vals)),
#     var_labs = scientific(var1_vals), name_lab = "Probability of missegregation",
#     plot_WGD = FALSE,
#     n_simulations = n_simulations_per_batch,
#     plotname = paste0(model_prefix, "_prob_CN_missegregation_varies_and_scale_selection=", var2_fixed),
#     example_simulation = FALSE
# )
```

```{r}
# var1_fixed <- var1_vals[length(var1_vals)]
# statistics_multivar_vector(
#     model_prefix = model_prefix, folder_workplace = folder_workplace,
#     var1_name = var1_name, var1_vals = rep(var1_fixed, length(var2_vals)),
#     var2_name = var2_name, var2_labs = var2_labs,
#     var_labs = var2_labs, name_lab = "Scale of selection rates",
#     plot_WGD = FALSE,
#     n_simulations = n_simulations_per_batch,
#     plotname = paste0(model_prefix, "_scale_selection_varies_and_prob_CN_missegregation=", var1_fixed),
#     example_simulation = FALSE
# )
```



```{r}
```
