```{r setup}
#-----------------------------------------------------------------------
setwd("/Users/dinhngockhanh/CancerSimulator/R/")
files_sources <- list.files(pattern = "*.r$")
sapply(files_sources, source)
#-----------------------------------------------------------------------
# devtools::install_github("dinhngockhanh/CancerSimulator")
# library(CancerSimulator)
```



```{r,fig.height=5,fig.width=10}
cell_lifespan <- 1
T_0 <- list(0, "day")
T_end <- list(300, "day")
Table_sample <- data.frame(Sample_ID = c("SA"), Cell_count = c(Inf), Age_sample = c(T_end[[1]]))

T_tau_step <- cell_lifespan / 2
CN_bin_length <- 500000

selection_model <- "chrom-arm-selection"

prob_CN_whole_genome_duplication <- 0
prob_CN_missegregation <- 0
prob_CN_chrom_arm_missegregation <- 0
prob_CN_focal_amplification <- 0
prob_CN_focal_deletion <- 0
prob_CN_cnloh_interstitial <- 0
prob_CN_cnloh_terminal <- 0
model_CN_focal_amplification_length <- "beta"
model_CN_focal_deletion_length <- "beta"
prob_CN_focal_amplification_length_shape_1 <- 0.758304780825031
prob_CN_focal_amplification_length_shape_2 <- 5.33873409782625
prob_CN_focal_deletion_length_shape_1 <- 0.814054548726361
prob_CN_focal_deletion_length_shape_2 <- 6.16614890284825
prob_CN_cnloh_interstitial_length <- 0.005
prob_CN_cnloh_terminal_length <- 0.005
rate_driver <- 0
rate_passenger <- 1e-11

bound_driver <- 3
bound_average_ploidy <- 4.5
bound_maximum_CN <- 8
bound_homozygosity <- 0

vec_time <- T_0[[1]]:T_end[[1]]
vec_cell_count <- rep(1000,length(vec_time))
table_population_dynamics <- cbind(vec_time, vec_cell_count)

gc <- read.csv(file = system.file("extdata", "gc_map_500kb.csv", package = "CancerSimulator"))
gc_slope <- 1.2
gc_int <- 0
sigma1 <- 0.02642392
num_reads <- 3906632

model_variables_base <- BUILD_general_variables(
    cell_lifespan = cell_lifespan,
    T_0 = T_0, T_end = T_end, T_tau_step = T_tau_step,
    Table_sample = Table_sample,
    CN_bin_length = CN_bin_length,

    prob_CN_whole_genome_duplication = prob_CN_whole_genome_duplication,
    prob_CN_missegregation = prob_CN_missegregation,
    prob_CN_chrom_arm_missegregation = prob_CN_chrom_arm_missegregation,
    prob_CN_focal_amplification = prob_CN_focal_amplification,
    prob_CN_focal_deletion = prob_CN_focal_deletion,
    prob_CN_cnloh_interstitial = prob_CN_cnloh_interstitial,
    prob_CN_cnloh_terminal = prob_CN_cnloh_terminal,

    model_CN_focal_amplification_length = model_CN_focal_amplification_length,
    model_CN_focal_deletion_length = model_CN_focal_deletion_length,
    prob_CN_focal_amplification_length_shape_1 = prob_CN_focal_amplification_length_shape_1,
    prob_CN_focal_amplification_length_shape_2 = prob_CN_focal_amplification_length_shape_2,
    prob_CN_focal_deletion_length_shape_1 = prob_CN_focal_deletion_length_shape_1,
    prob_CN_focal_deletion_length_shape_2 = prob_CN_focal_deletion_length_shape_2,
    prob_CN_cnloh_interstitial_length = prob_CN_cnloh_interstitial_length,
    prob_CN_cnloh_terminal_length = prob_CN_cnloh_terminal_length,
    rate_driver = rate_driver,
    rate_passenger = rate_passenger,
    selection_model = selection_model,
    bound_driver = bound_driver,
    bound_average_ploidy = bound_average_ploidy,
    bound_maximum_CN = bound_maximum_CN,
    bound_homozygosity = bound_homozygosity,
    table_population_dynamics = table_population_dynamics,
    gc = gc,
    gc_slope = gc_slope,
    gc_int = gc_int,
    sigma1 = sigma1,
    num_reads = num_reads
)

arm_id <- c(paste(model_variables_base$cn_info$Chromosome, "p", sep = ""), paste(model_variables_base$cn_info$Chromosome, "q", sep = ""))
arm_chromosome <- rep(model_variables_base$cn_info$Chromosome, 2)
arm_start <- c(rep(1, length(model_variables_base$cn_info$Chromosome)), model_variables_base$cn_info$Centromere_location + 1)
arm_end <- c(model_variables_base$cn_info$Centromere_location, model_variables_base$cn_info$Bin_count)
arm_s <- rep(1, length(arm_id))

delta_selection <- c(0.25, 0.5)
delta_sel_gain_per_arm <- sqrt(1 + delta_selection[1]) - 1
delta_sel_loss_per_arm <- sqrt(1 + delta_selection[2]) - 1
chrom_gains <- sample(model_variables_base$cn_info$Chromosome, round(length(model_variables_base$cn_info$Chromosome) / 2), replace = FALSE)
chrom_losses <- setdiff(model_variables_base$cn_info$Chromosome, chrom_gains)
arm_s[which(arm_chromosome %in% chrom_gains)] <- 1 + delta_sel_gain_per_arm
arm_s[which(arm_chromosome %in% chrom_losses)] <- 1 / (1 + delta_sel_loss_per_arm)

model_variables_base <- BUILD_driver_library(
    model_variables = model_variables_base,
    table_arm_selection_rates = data.frame(Arm_ID = arm_id, Chromosome = arm_chromosome, Bin_start = arm_start, Bin_end = arm_end, s_rate = arm_s)
)

cell_count <- 1000
CN_matrix <- BUILD_cn_normal_XX(model_variables_base$cn_info)
drivers <- list()
model_variables_base <- BUILD_initial_population(
    model_variables = model_variables_base,
    cell_count = cell_count,
    CN_matrix = CN_matrix,
    drivers = drivers
)

model_prefix <- "SPECTRUM"
folder_workplace <- model_prefix
```



```{r}
n_simulations <- 30

var1_name <- "prob_CN_missegregation"
var1_vals <- seq(1e-3, 1e-2, by = 1e-3)

var2_name <- "prob_CN_whole_genome_duplication"
var2_vals <- seq(1e-3, 1e-2, by = 1e-3)

extra_var <- list(
    "prob_neutral_CN_missegregation/prob_CN_missegregation", 10
)
```

```{r}
simulator_multivar(
    model_prefix = model_prefix, folder_workplace = folder_workplace,
    model_variables_base = model_variables_base,
    var1_name = var1_name, var1_vals = var1_vals,
    var2_name = var2_name, var2_vals = var2_vals,
    extra_var = extra_var,
    n_simulations = n_simulations,
    plot = FALSE,
    neutral_variations = TRUE, save_cn_profile = TRUE,
    save_newick_tree = TRUE, model_readcount = TRUE,
    compute_parallel = TRUE
)
```



```{r}

```
